# https://docs.docker.com/compose/how-tos/production/
# https://docs.docker.com/compose/how-tos/multiple-compose-files/merge/
# https://docs.docker.com/reference/compose-file/merge/

services:
  backend:
    # todo: env.prodを追加
    volumes: !reset []
    entrypoint: !override "/usr/src/app/entrypoint.sh"
    environment: !override
      - ENVIRONMENT=production
    development: !reset []
    ports: !reset []

  db:
    volumes: !reset []

  frontend:
    environment: !override
      - BACKEND_HOST=https://localhost:443/api
      - BACKEND_WS_HOST=wss://localhost:443/ws
    ports: !reset []

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: web
    ports:
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    command: ["nginx", "-g", "daemon off;"]

include:
  - ./elk/elk-services.yml
