# Generated by Django 5.1.3 on 2024-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media",
                verbose_name="プロフィール画像",
            ),
        ),
    ]
