# Generated by Django 5.1.4 on 2024-12-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websocket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="action",
            field=models.CharField(default="waiting", max_length=50),
        ),
        migrations.AlterField(
            model_name="gamestate",
            name="game_state",
            field=models.JSONField(),
        ),
    ]
