# Generated by Django 5.1.4 on 2024-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_rename_torunament_match_tournament"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("tournament", "match_number"), name="unique_match_number"
            ),
        ),
    ]
