# Generated by Django 5.1.4 on 2024-12-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_match_unique_match_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player1",
                to="tournament.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player1_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player2",
                to="tournament.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="PlayerMatch",
        ),
    ]
